IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_START_HEIGHT: 335
  ROI_HEIGHT: 40

XYCAR:
  START_SPEED: 4.0
  MAX_SPEED: 4.0
  MIN_SPEED: 3.0
  SPEED_CONTROL_THRESHOLD: 5.0
  ACCELERATION_STEP: 0.1
  DECELERATION_STEP: 0.05
CTE:
  CTE_ERROR: 0.240

PID:
  CURVE_P_GAIN: 0.38
  CURVE_I_GAIN: 0.00001
  CURVE_D_GAIN: 0.025
  P_GAIN: 0.38
  I_GAIN: 0.00001
  D_GAIN: 0.01

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 10

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  SUB_LIDAR: /scan
  SUB_OBJECT: /object_detect
  QUEUE_SIZE: 1
  QUEUE_SIZE_LIDAR: 10

CANNY:
  LOW_THRESHOLD: 60
  HIGH_THRESHOLD: 250

HOUGH:
  ABS_SLOPE_RANGE: 10.0
  THRESHOLD: 25
  MIN_LINE_LENGTH: 25
  MAX_LINE_GAP: 10

LIDAR:
  OBS_THRESHOLD: 35
  STATIC_THRESHOLD: 35

DEBUG: false